public class Gerador extends Pokemon{
    public static Pokemon[] pkmn = new Pokemon[152];
    Pokemon pkmn1 = new Pokemon();
    Pokemon pkmn2 = new Pokemon();
    Pokemon pkmn3 = new Pokemon();
    Pokemon pkmn4 = new Pokemon();
    Pokemon pkmn5 = new Pokemon();
    Pokemon pkmn6 = new Pokemon();
    Pokemon pkmn7 = new Pokemon();
    Pokemon pkmn8 = new Pokemon();
    Pokemon pkmn9 = new Pokemon();
    Pokemon pkmn10 = new Pokemon();
    Pokemon pkmn11 = new Pokemon();
    Pokemon pkmn12 = new Pokemon();
    Pokemon pkmn13 = new Pokemon();
    Pokemon pkmn14 = new Pokemon();
    Pokemon pkmn15 = new Pokemon();
    Pokemon pkmn16 = new Pokemon();
    Pokemon pkmn17 = new Pokemon();
    Pokemon pkmn18 = new Pokemon();
    Pokemon pkmn19 = new Pokemon();
    Pokemon pkmn20 = new Pokemon();
    Pokemon pkmn21 = new Pokemon();
    Pokemon pkmn22 = new Pokemon();
    Pokemon pkmn23 = new Pokemon();
    Pokemon pkmn24 = new Pokemon();
    Pokemon pkmn25 = new Pokemon();
    Pokemon pkmn26 = new Pokemon();
    Pokemon pkmn27 = new Pokemon();
    Pokemon pkmn28 = new Pokemon();
    Pokemon pkmn29 = new Pokemon();
    Pokemon pkmn30 = new Pokemon();
    Pokemon pkmn31 = new Pokemon();
    Pokemon pkmn32 = new Pokemon();
    Pokemon pkmn33 = new Pokemon();
    Pokemon pkmn34 = new Pokemon();
    Pokemon pkmn35 = new Pokemon();
    Pokemon pkmn36 = new Pokemon();
    Pokemon pkmn37 = new Pokemon();
    Pokemon pkmn38 = new Pokemon();
    Pokemon pkmn39 = new Pokemon();
    Pokemon pkmn40 = new Pokemon();
    Pokemon pkmn41 = new Pokemon();
    Pokemon pkmn42 = new Pokemon();
    Pokemon pkmn43 = new Pokemon();
    Pokemon pkmn44 = new Pokemon();
    Pokemon pkmn45 = new Pokemon();
    Pokemon pkmn46 = new Pokemon();
    Pokemon pkmn47 = new Pokemon();
    Pokemon pkmn48 = new Pokemon();
    Pokemon pkmn49 = new Pokemon();
    Pokemon pkmn50 = new Pokemon();
    Pokemon pkmn51 = new Pokemon();
    Pokemon pkmn52 = new Pokemon();
    Pokemon pkmn53 = new Pokemon();
    Pokemon pkmn54 = new Pokemon();
    Pokemon pkmn55 = new Pokemon();
    Pokemon pkmn56 = new Pokemon();
    Pokemon pkmn57 = new Pokemon();
    Pokemon pkmn58 = new Pokemon();
    Pokemon pkmn59 = new Pokemon();
    Pokemon pkmn60 = new Pokemon();
    Pokemon pkmn61 = new Pokemon();
    Pokemon pkmn62 = new Pokemon();
    Pokemon pkmn63 = new Pokemon();
    Pokemon pkmn64 = new Pokemon();
    Pokemon pkmn65 = new Pokemon();
    Pokemon pkmn66 = new Pokemon();
    Pokemon pkmn67 = new Pokemon();
    Pokemon pkmn68 = new Pokemon();
    Pokemon pkmn69 = new Pokemon();
    Pokemon pkmn70 = new Pokemon();
    Pokemon pkmn71 = new Pokemon();
    Pokemon pkmn72 = new Pokemon();
    Pokemon pkmn73 = new Pokemon();
    Pokemon pkmn74 = new Pokemon();
    Pokemon pkmn75 = new Pokemon();
    Pokemon pkmn76 = new Pokemon();
    Pokemon pkmn77 = new Pokemon();
    Pokemon pkmn78 = new Pokemon();
    Pokemon pkmn79 = new Pokemon();
    Pokemon pkmn80 = new Pokemon();
    Pokemon pkmn81 = new Pokemon();
    Pokemon pkmn82 = new Pokemon();
    Pokemon pkmn83 = new Pokemon();
    Pokemon pkmn84 = new Pokemon();
    Pokemon pkmn85 = new Pokemon();
    Pokemon pkmn86 = new Pokemon();
    Pokemon pkmn87 = new Pokemon();
    Pokemon pkmn88 = new Pokemon();
    Pokemon pkmn89 = new Pokemon();
    Pokemon pkmn90 = new Pokemon();
    Pokemon pkmn91 = new Pokemon();
    Pokemon pkmn92 = new Pokemon();
    Pokemon pkmn93 = new Pokemon();
    Pokemon pkmn94 = new Pokemon();
    Pokemon pkmn95 = new Pokemon();
    Pokemon pkmn96 = new Pokemon();
    Pokemon pkmn97 = new Pokemon();
    Pokemon pkmn98 = new Pokemon();
    Pokemon pkmn99 = new Pokemon();
    Pokemon pkmn100 = new Pokemon();
    Pokemon pkmn101 = new Pokemon();
    Pokemon pkmn102 = new Pokemon();
    Pokemon pkmn103 = new Pokemon();
    Pokemon pkmn104 = new Pokemon();
    Pokemon pkmn105 = new Pokemon();
    Pokemon pkmn106 = new Pokemon();
    Pokemon pkmn107 = new Pokemon();
    Pokemon pkmn108 = new Pokemon();
    Pokemon pkmn109 = new Pokemon();
    Pokemon pkmn110 = new Pokemon();
    Pokemon pkmn111 = new Pokemon();
    Pokemon pkmn112 = new Pokemon();
    Pokemon pkmn113 = new Pokemon();
    Pokemon pkmn114 = new Pokemon();
    Pokemon pkmn115 = new Pokemon();
    Pokemon pkmn116 = new Pokemon();
    Pokemon pkmn117 = new Pokemon();
    Pokemon pkmn118 = new Pokemon();
    Pokemon pkmn119 = new Pokemon();
    Pokemon pkmn120 = new Pokemon();
    Pokemon pkmn121 = new Pokemon();
    Pokemon pkmn122 = new Pokemon();
    Pokemon pkmn123 = new Pokemon();
    Pokemon pkmn124 = new Pokemon();
    Pokemon pkmn125 = new Pokemon();
    Pokemon pkmn126 = new Pokemon();
    Pokemon pkmn127 = new Pokemon();
    Pokemon pkmn128 = new Pokemon();
    Pokemon pkmn129 = new Pokemon();
    Pokemon pkmn130 = new Pokemon();
    Pokemon pkmn131 = new Pokemon();
    Pokemon pkmn132 = new Pokemon();
    Pokemon pkmn133 = new Pokemon();
    Pokemon pkmn134 = new Pokemon();
    Pokemon pkmn135 = new Pokemon();
    Pokemon pkmn136 = new Pokemon();
    Pokemon pkmn137 = new Pokemon();
    Pokemon pkmn138 = new Pokemon();
    Pokemon pkmn139 = new Pokemon();
    Pokemon pkmn140 = new Pokemon();
    Pokemon pkmn141 = new Pokemon();
    Pokemon pkmn142 = new Pokemon();
    Pokemon pkmn143 = new Pokemon();
    Pokemon pkmn144 = new Pokemon();
    Pokemon pkmn145 = new Pokemon();
    Pokemon pkmn146 = new Pokemon();
    Pokemon pkmn147 = new Pokemon();
    Pokemon pkmn148 = new Pokemon();
    Pokemon pkmn149 = new Pokemon();
    Pokemon pkmn150 = new Pokemon();
    Pokemon pkmn151 = new Pokemon();

    public Pokemon createPokemons(int index){
        pkmn[1] = pkmn1 = new Pokemon(1, "Bulbasaur", "Grass", "Poison");
        pkmn[2] = pkmn2 = new Pokemon(2, "Ivysaur", "Grass", "Poison");
        pkmn[3] = pkmn3 = new Pokemon(3, "Venusaur", "Grass", "Poison");
        pkmn[4] = pkmn4 = new Pokemon(4, "Charmander", "Fire", "-");
        pkmn[5] = pkmn5 = new Pokemon(5, "Charmeleon", "Fire", "-");
        pkmn[6] = pkmn6 = new Pokemon(6, "Charizard", "Fire", "Flying");
        pkmn[7] = pkmn7 = new Pokemon(7, "Squirtle", "Water", "-");
        pkmn[8] = pkmn8 = new Pokemon(8, "Wartortle", "Water", "-");
        pkmn[9] = pkmn9 = new Pokemon(9, "Blastoise", "Water", "-");
        pkmn[10] = pkmn10 = new Pokemon(10, "Caterpie", "Bug", "-");
        pkmn[11] = pkmn11 = new Pokemon(11, "Metapod", "Bug", "-");
        pkmn[12] = pkmn12 = new Pokemon(12, "Butterfree", "Bug", "Flying");
        pkmn[13] = pkmn13 = new Pokemon(13, "Weedle", "Bug", "Poison");
        pkmn[14] = pkmn14 = new Pokemon(14, "Kakuna", "Bug", "Poison");
        pkmn[15] = pkmn15 = new Pokemon(15, "Beedrill", "Bug", "Poison");
        pkmn[16] = pkmn16 = new Pokemon(16, "Pidgey", "Normal", "Flying");
        pkmn[17] = pkmn17 = new Pokemon(17, "Pidgeotto", "Normal", "Flying");
        pkmn[18] = pkmn18 = new Pokemon(18, "Pidgeot", "Normal", "Flying");
        pkmn[19] = pkmn19 = new Pokemon(19, "Rattata", "Normal", "-");
        pkmn[20] = pkmn20 = new Pokemon(20, "Raticate", "Normal", "-");
        pkmn[21] = pkmn21 = new Pokemon(21, "Spearow", "Flying", "-");
        pkmn[22] = pkmn22 = new Pokemon(22, "Fearow", "Normal", "Flying");
        pkmn[23] = pkmn23 = new Pokemon(23, "Ekans", "Poison", "-");
        pkmn[24] = pkmn24 = new Pokemon(24, "Arbok", "Poison", "-");
        pkmn[25] = pkmn25 = new Pokemon(25, "Pikachu", "Electric", "-");
        pkmn[26] = pkmn26 = new Pokemon(26, "Raichu", "Electric", "-");
        pkmn[27] = pkmn27 = new Pokemon(27, "Sandshrew", "Ground", "-");
        pkmn[28] = pkmn28 = new Pokemon(28, "Sandslash", "Ground", "-");
        pkmn[29] = pkmn29 = new Pokemon(29, "Nidoran_Female", "Poison", "-");
        pkmn[30] = pkmn30 = new Pokemon(30, "Nidorina", "Poison", "-");
        pkmn[31] = pkmn31 = new Pokemon(31, "Nidoqueen", "Poison", "Ground");
        pkmn[32] = pkmn32 = new Pokemon(32, "Nidoran_Male", "Poison", "-");
        pkmn[33] = pkmn33 = new Pokemon(33, "Nidorino", "Poison", "-");
        pkmn[34] = pkmn34 = new Pokemon(34, "Nidoking", "Poison", "Ground");
        pkmn[35] = pkmn35 = new Pokemon(35, "Clefairy", "Normal", "-");
        pkmn[36] = pkmn36 = new Pokemon(36, "Clefable", "Normal", "-");
        pkmn[37] = pkmn37 = new Pokemon(37, "Vulpix", "Fire", "-");
        pkmn[38] = pkmn38 = new Pokemon(38, "Ninetales", "Fire", "-");
        pkmn[39] = pkmn39 = new Pokemon(39, "Jigglypuff", "Normal", "-");
        pkmn[40] = pkmn40 = new Pokemon(40, "Wigglytuff", "Normal", "-");
        pkmn[41] = pkmn41 = new Pokemon(41, "Zubat", "Poison", "Flying");
        pkmn[42] = pkmn42 = new Pokemon(42, "Golbat", "Poison", "Flying");
        pkmn[43] = pkmn43 = new Pokemon(43, "Oddish", "Grass", "Poison");
        pkmn[44] = pkmn44 = new Pokemon(44, "Gloom", "Grass", "Poison");
        pkmn[45] = pkmn45 = new Pokemon(45, "Vileplume", "Grass", "Poison");
        pkmn[46] = pkmn46 = new Pokemon(46, "Paras", "Bug", "Grass");
        pkmn[47] = pkmn47 = new Pokemon(47, "Parasect", "Bug", "Grass");
        pkmn[48] = pkmn48 = new Pokemon(48, "Venonat", "Bug", "Poison");
        pkmn[49] = pkmn49 = new Pokemon(49, "Venomoth", "Bug", "Poison");
        pkmn[50] = pkmn50 = new Pokemon(50, "Diglett", "Ground", "-");
        pkmn[51] = pkmn51 = new Pokemon(51, "Dugtrio", "Ground", "-");
        pkmn[52] = pkmn52 = new Pokemon(52, "Meowth", "Normal", "-");
        pkmn[53] = pkmn53 = new Pokemon(53, "Persian", "Normal", "-");
        pkmn[54] = pkmn54 = new Pokemon(54, "Psyduck", "Water", "-");
        pkmn[55] = pkmn55 = new Pokemon(55, "Golduck", "Water", "-");
        pkmn[56] = pkmn56 = new Pokemon(56, "Mankey", "Fighting", "-");
        pkmn[57] = pkmn57 = new Pokemon(57, "Primeape", "Fighting", "-");
        pkmn[58] = pkmn58 = new Pokemon(58, "Growlithe", "Fire", "-");
        pkmn[59] = pkmn59 = new Pokemon(59, "Arcanine", "Fire", "-");
        pkmn[60] = pkmn60 = new Pokemon(60, "Poliwag", "Water", "-");
        pkmn[61] = pkmn61 = new Pokemon(61, "Poliwhirl", "Water", "-");
        pkmn[62] = pkmn62 = new Pokemon(62, "Poliwrath", "Water", "Fighting");
        pkmn[63] = pkmn63 = new Pokemon(63, "Abra", "Psychic", "-");
        pkmn[64] = pkmn64 = new Pokemon(64, "Kadabra", "Psychic", "-");
        pkmn[65] = pkmn65 = new Pokemon(65, "Alakazam", "Psychic", "-");
        pkmn[66] = pkmn66 = new Pokemon(66, "Machop", "Fighting", "-");
        pkmn[67] = pkmn67 = new Pokemon(67, "Machoke", "Fighting", "-");
        pkmn[68] = pkmn68 = new Pokemon(68, "Machamp", "Fighting", "-");
        pkmn[69] = pkmn69 = new Pokemon(69, "Bellsprout", "Grass", "Poison");
        pkmn[70] = pkmn70 = new Pokemon(70, "Weepinbell", "Grass", "Poison");
        pkmn[71] = pkmn71 = new Pokemon(71, "Victreebel", "Grass", "Poison");
        pkmn[72] = pkmn72 = new Pokemon(72, "Tentacool", "Water", "Poison");
        pkmn[73] = pkmn73 = new Pokemon(73, "Tentacruel", "Water", "Poison");
        pkmn[74] = pkmn74 = new Pokemon(74, "Geodude", "Rock", "Ground");
        pkmn[75] = pkmn75 = new Pokemon(75, "Graveler", "Rock", "Ground");
        pkmn[76] = pkmn76 = new Pokemon(76, "Golem", "Rock", "Ground");
        pkmn[77] = pkmn77 = new Pokemon(77, "Ponyta", "Fire", "-");
        pkmn[78] = pkmn78 = new Pokemon(78, "Rapidash", "Fire", "-");
        pkmn[79] = pkmn79 = new Pokemon(79, "Slowpoke", "Water", "Psychic");
        pkmn[80] = pkmn80 = new Pokemon(80, "Slowbro", "Water", "Psychic");
        pkmn[81] = pkmn81 = new Pokemon(81, "Magnemite", "Electric", "-");
        pkmn[82] = pkmn82 = new Pokemon(82, "Magneton", "Electric", "-");
        pkmn[83] = pkmn83 = new Pokemon(83, "Farfetch'd", "Normal", "Flying");
        pkmn[84] = pkmn84 = new Pokemon(84, "Doduo", "Normal", "Flying");
        pkmn[85] = pkmn85 = new Pokemon(85, "Dodrio", "Normal", "Flying");
        pkmn[86] = pkmn86 = new Pokemon(86, "Seel", "Water", "-");
        pkmn[87] = pkmn87 = new Pokemon(87, "Dewgong", "Water", "Ice");
        pkmn[88] = pkmn88 = new Pokemon(88, "Grimer", "Poison", "-");
        pkmn[89] = pkmn89 = new Pokemon(89, "Muk", "Poison", "-");
        pkmn[90] = pkmn90 = new Pokemon(90, "Shellder", "Water", "-");
        pkmn[91] = pkmn91 = new Pokemon(91, "Cloyster", "Water", "Ice");
        pkmn[92] = pkmn92 = new Pokemon(92, "Gastly", "Ghost", "Poison");
        pkmn[93] = pkmn93 = new Pokemon(93, "Haunter", "Ghost", "Poison");
        pkmn[94] = pkmn94 = new Pokemon(94, "Gengar", "Ghost", "Poison");
        pkmn[95] = pkmn95 = new Pokemon(95, "Onix", "Rock", "Ground");
        pkmn[96] = pkmn96 = new Pokemon(96, "Drowzee", "Psychic", "-");
        pkmn[97] = pkmn97 = new Pokemon(97, "Hypno", "Psychic", "-");
        pkmn[98] = pkmn98 = new Pokemon(98, "Krabby", "Water", "-");
        pkmn[99] = pkmn99 = new Pokemon(99, "Kingler", "Water", "-");
        pkmn[100] = pkmn100 = new Pokemon(100, "Voltorb", "Electric", "-");
        pkmn[101] = pkmn101 = new Pokemon(101, "Electrode", "Electric", "-");
        pkmn[102] = pkmn102 = new Pokemon(102, "Exeggcute", "Grass", "Psychic");
        pkmn[103] = pkmn103 = new Pokemon(103, "Exeggutor", "Grass", "Psychic");
        pkmn[104] = pkmn104 = new Pokemon(104, "Cubone", "Ground", "-");
        pkmn[105] = pkmn105 = new Pokemon(105, "Marowak", "Ground", "-");
        pkmn[106] = pkmn106 = new Pokemon(106, "Hitmonlee", "Fighting", "-");
        pkmn[107] = pkmn107 = new Pokemon(107, "Hitmonchan", "Fighting", "-");
        pkmn[108] = pkmn108 = new Pokemon(108, "Lickitung", "Normal", "-");
        pkmn[109] = pkmn109 = new Pokemon(109, "Koffing", "Poison", "-");
        pkmn[110] = pkmn110 = new Pokemon(110, "Weezing", "Poison", "-");
        pkmn[111] = pkmn111 = new Pokemon(111, "Rhyhorn", "Ground", "Rock");
        pkmn[112] = pkmn112 = new Pokemon(112, "Rhydon", "Ground", "Rock");
        pkmn[113] = pkmn113 = new Pokemon(113, "Chansey", "Normal", "-");
        pkmn[114] = pkmn114 = new Pokemon(114, "Tangela", "Grass", "-");
        pkmn[115] = pkmn115 = new Pokemon(115, "Kangaskhan", "Normal", "-");
        pkmn[116] = pkmn116 = new Pokemon(116, "Horsea", "Water", "-");
        pkmn[117] = pkmn117 = new Pokemon(117, "Seadra", "Water", "-");
        pkmn[118] = pkmn118 = new Pokemon(118, "Goldeen", "Water", "-");
        pkmn[119] = pkmn119 = new Pokemon(119, "Seaking", "Water", "-");
        pkmn[120] = pkmn120 = new Pokemon(120, "Staryu", "Water", "-");
        pkmn[121] = pkmn121 = new Pokemon(121, "Starmie", "Water", "Psychic");
        pkmn[122] = pkmn122 = new Pokemon(122, "Mr_Mime", "Psychic", "-");
        pkmn[123] = pkmn123 = new Pokemon(123, "Scyther", "Bug", "Flying");
        pkmn[124] = pkmn124 = new Pokemon(124, "Jynx", "Ice", "Psychic");
        pkmn[125] = pkmn125 = new Pokemon(125, "Electabuzz", "Electric", "-");
        pkmn[126] = pkmn126 = new Pokemon(126, "Magmar", "Fire", "-");
        pkmn[127] = pkmn127 = new Pokemon(127, "Pinsir", "Bug", "-");
        pkmn[128] = pkmn128 = new Pokemon(128, "Tauros", "Normal", "-");
        pkmn[129] = pkmn129 = new Pokemon(129, "Magikarp", "Water", "-");
        pkmn[130] = pkmn130 = new Pokemon(130, "Gyarados", "Water", "Flying");
        pkmn[131] = pkmn131 = new Pokemon(131, "Lapras", "Water", "Ice");
        pkmn[132] = pkmn132 = new Pokemon(132, "Ditto", "Normal", "-");
        pkmn[133] = pkmn133 = new Pokemon(133, "Eevee", "Normal", "-");
        pkmn[134] = pkmn134 = new Pokemon(134, "Vaporeon", "Water", "-");
        pkmn[135] = pkmn135 = new Pokemon(135, "Jolteon", "Electric", "-");
        pkmn[136] = pkmn136 = new Pokemon(136, "Flareon", "Fire", "-");
        pkmn[137] = pkmn137 = new Pokemon(137, "Porygon", "Normal", "-");
        pkmn[138] = pkmn138 = new Pokemon(138, "Omanyte", "Rock", "Water");
        pkmn[139] = pkmn139 = new Pokemon(139, "Omastar", "Rock", "Water");
        pkmn[140] = pkmn140 = new Pokemon(140, "Kabuto", "Rock", "Water");
        pkmn[141] = pkmn141 = new Pokemon(141, "Kabutops", "Rock", "Water");
        pkmn[142] = pkmn142 = new Pokemon(142, "Aerodactyl", "Rock", "Flying");
        pkmn[143] = pkmn143 = new Pokemon(143, "Snorlax", "Normal", "-");
        pkmn[144] = pkmn144 = new Pokemon(144, "Articuno", "Ice", "Flying");
        pkmn[145] = pkmn145 = new Pokemon(145, "Zapdos", "Electric", "Flying");
        pkmn[146] = pkmn146 = new Pokemon(146, "Moltres", "Fire", "Flying");
        pkmn[147] = pkmn147 = new Pokemon(147, "Dratini", "Dragon", "-");
        pkmn[148] = pkmn148 = new Pokemon(148, "Dragonair", "Dragon", "-");
        pkmn[149] = pkmn149 = new Pokemon(149, "Dragonite", "Dragon", "Flying");
        pkmn[150] = pkmn150 = new Pokemon(150, "Mewtwo", "Psychic", "-");
        pkmn[151] = pkmn151 = new Pokemon(151, "Mew", "Psychic", "-");
        return pkmn[index];
    }
}
